[build]
  publish = "public"
  functions = "netlify/functions"
  command = ""

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
